FROM ghcr.io/cyberworm-uk/lyrebird:latest AS bin

FROM docker.io/library/alpine:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine:latest"
LABEL org.opencontainers.image.title="Tor (Alpine)"
LABEL org.opencontainers.image.description="Tor (Alpine) image"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/container.git"
RUN apk --no-cache --no-interactive add tor
COPY torrc /etc/tor/torrc-defaults
COPY --from=bin /lyrebird /usr/bin/lyrebird
VOLUME [ "/var/lib/tor" ]
ENTRYPOINT [ "/usr/bin/tor" ]