FROM docker.io/library/rust:alpine AS build
ENV RUSTFLAGS="-C target-feature=-crt-static"
ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
RUN apk --no-interactive add musl-dev pkgconfig openssl-dev sqlite-dev xz-dev
RUN cargo install --locked --features=full arti

FROM docker.io/library/alpine:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine:latest"
LABEL org.opencontainers.image.title="Arti (Tor)"
LABEL org.opencontainers.image.description="Arti (Tor) Rust implementation of Tor"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
RUN apk --no-cache --no-interactive add xz-libs sqlite-libs libgcc && \
    addgroup -S arti && \
    adduser -h /arti -S arti -G arti
COPY arti.toml /arti/config/arti/arti.toml
USER arti:arti
ENV XDG_CONFIG_HOME /arti/config
ENV XDG_DATA_HOME /arti/data
VOLUME [ "/arti" ]
COPY --from=build /usr/local/cargo/bin/arti /usr/bin/arti
COPY --from=bin /lyrebird /usr/bin/lyrebird
ENTRYPOINT [ "/usr/bin/arti", "proxy" ]