FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/go:latest AS build
ARG TARGETOS TARGETARCH VERSION=2.1.7
RUN git clone --depth=1 -b ${VERSION} https://github.com/DNSCrypt/dnscrypt-proxy.git
ENV GOOS="$TARGETOS" GOARCH="$TARGETARCH" GOFLAGS="-buildvcs=false -trimpath"
WORKDIR /dnscrypt-proxy/dnscrypt-proxy
RUN --mount=type=cache,target=/go/pkg go mod download
RUN --mount=type=cache,target=/go/pkg --mount=type=cache,target=/root/.cache/go-build go build -o /a.out -ldflags '-w -s -buildid=' .

FROM cgr.dev/chainguard/wolfi-base:latest
LABEL org.opencontainers.image.base.name="cgr.dev/chainguard/wolfi-base"
LABEL org.opencontainers.image.title="DNSCrypt Proxy (Resolver)"
LABEL org.opencontainers.image.description="DNSCrypt Proxy (Resolver) built as part of DOHOT"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
RUN mkdir -p /etc/dnscrypt-proxy/ /var/log/dnscrypt-proxy/ && \
  chown nonroot:nonroot /var/log/dnscrypt-proxy/
EXPOSE 5054/udp
EXPOSE 5054/tcp
VOLUME [ "/var/log/dnscrypt-proxy/" ]
COPY dnscrypt-proxy.toml /etc/dnscrypt-proxy/dnscrypt-proxy.toml
COPY --from=build /a.out /usr/bin/dnscrypt-proxy

RUN touch -t @0 /var/log/dnscrypt-proxy /etc/dnscrypt-proxy /etc/dnscrypt-proxy/dnscrypt-proxy.toml /usr/bin/dnscrypt-proxy

USER nonroot
ENTRYPOINT [ "/usr/bin/dnscrypt-proxy", "-config", "/etc/dnscrypt-proxy/dnscrypt-proxy.toml" ]