FROM ghcr.io/cyberworm-uk/tor-base:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine:latest"
LABEL org.opencontainers.image.title="Tor Bridge Proxy"
LABEL org.opencontainers.image.description="Tor Bridge Proxy (Client) for meek_lite, obfs2, obfs3, obfs4, scramblesuit, snowflake and webtunnel"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
EXPOSE 9050
ENTRYPOINT [ "/usr/bin/tor", \
    "--socksport", "0.0.0.0:9050", \
    "--usebridges", "1" \
]