FROM --platform=$BUILDPLATFORM docker.io/library/golang:alpine AS build
WORKDIR /go/src
RUN apk add --no-cache git && git clone --depth=1 https://github.com/cyberworm-uk/mailu-quadlet.git .
ARG TARGETOS TARGETARCH
ENV GOOS="$TARGETOS" GOARCH="$TARGETARCH" GOFLAGS="-buildvcs=false -trimpath" CGO_ENABLED=0
RUN --mount=type=cache,target=/go/pkg go mod download
RUN --mount=type=cache,target=/go/pkg --mount=type=cache,target=/root/.cache/go-build go build -ldflags "-w -s -buildid=" ./cmd/cli

FROM scratch
VOLUME /data
WORKDIR /data
COPY --from=build /go/src/cli /cli
ENTRYPOINT [ "/cli" ]
