FROM docker.io/library/rust:latest AS build
RUN cargo install doh-proxy --no-default-features

FROM cgr.dev/chainguard/wolfi-base:latest
LABEL org.opencontainers.image.base.name="cgr.dev/chainguard/wolfi-base"
LABEL org.opencontainers.image.title="DOH Proxy (Front)"
LABEL org.opencontainers.image.description="DOH Proxy (Front) built as an optional part of DOHOT"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
COPY --from=build /usr/local/cargo/bin/doh-proxy /usr/bin/doh-proxy
RUN touch -t @0 /usr/bin/doh-proxy
USER nonroot
ENTRYPOINT [ "/usr/bin/doh-proxy" ]