FROM ghcr.io/cyberworm-uk/tor-bridge-client:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine:latest"
LABEL org.opencontainers.image.title="Obfs4 Bridge"
LABEL org.opencontainers.image.description="Obfs4 (Lyrebird) Bridge/Server"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
RUN apk --no-cache --no-interactive add libcap-utils
EXPOSE 443
RUN setcap cap_net_bind_service=+ep /usr/bin/lyrebird
ENTRYPOINT [ "/usr/bin/tor", \
    "--bridgerelay", "1", \
    "--servertransportplugin", "obfs4 exec /usr/bin/lyrebird", \
    "--extorport", "auto", \
    "--servertransportlistenaddr", "obfs4 0.0.0.0:443" \
]