FROM ghcr.io/cyberworm-uk/tor-base:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine:latest"
LABEL org.opencontainers.image.title="Tor Proxy"
LABEL org.opencontainers.image.description="Tor Proxy (Client)"
LABEL org.opencontainers.image.source="https://github.com/cyberworm-uk/containers.git"
EXPOSE 9050
ENTRYPOINT [ "/usr/bin/tor", \
    "--socksport", \
    "0.0.0.0:9050" \
]