name: Docker Images (Arti)

on:
  schedule:
    - cron: '30 00 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push arti
        uses: docker/build-push-action@v6
        id: push
        with:
          context: tor/arti/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/arti:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/arti
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
