name: Docker Images (Dohot)

on:
#  schedule:
#    - cron: '30 00 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dnscrypt-proxy
        uses: docker/build-push-action@v6
        id: push-dnscrypt-proxy
        with:
          context: dohot/dnscrypt-proxy/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/dnscrypt-proxy:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-dnscrypt-proxy
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/dnscrypt-proxy
          subject-digest: ${{ steps.push-dnscrypt-proxy.outputs.digest }}
          push-to-registry: true

      - name: Build and push doh-proxy
        uses: docker/build-push-action@v6
        id: push-doh-proxy
        with:
          context: dohot/doh-proxy/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/doh-proxy:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-doh-proxy
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/doh-proxy
          subject-digest: ${{ steps.push-doh-proxy.outputs.digest }}
          push-to-registry: true