name: Docker Images (Tor)

on:
#  schedule:
#    - cron: '00 00 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push lyrebird
        uses: docker/build-push-action@v6
        id: push-lyrebird
        with:
          context: tor/lyrebird/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/lyrebird:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-lyrebird
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/lyrebird
          subject-digest: ${{ steps.push-lyrebird.outputs.digest }}
          push-to-registry: true

      - name: Build and push tor-base
        uses: docker/build-push-action@v6
        id: push-tor-base
        with:
          context: tor/tor-base/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tor-base:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-tor-base
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tor-base
          subject-digest: ${{ steps.push-tor-base.outputs.digest }}
          push-to-registry: true

      - name: Build and push tor-client
        uses: docker/build-push-action@v6
        id: push-tor-client
        with:
          context: tor/tor-client/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tor-client:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-tor-client
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tor-client
          subject-digest: ${{ steps.push-tor-client.outputs.digest }}
          push-to-registry: true

      - name: Build and push tor-bridge-client
        uses: docker/build-push-action@v6
        id: push-tor-bridge-client
        with:
          context: tor/tor-bridge-client/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tor-bridge-client:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-tor-bridge-client
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tor-bridge-client
          subject-digest: ${{ steps.push-tor-bridge-client.outputs.digest }}
          push-to-registry: true

      - name: Build and push tor-bridge-relay
        uses: docker/build-push-action@v6
        id: push-tor-bridge-relay
        with:
          context: tor/tor-bridge-relay/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tor-bridge-relay:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-tor-bridge-relay
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tor-bridge-relay
          subject-digest: ${{ steps.push-tor-bridge-relay.outputs.digest }}
          push-to-registry: true

      - name: Build and push snowflake-standalone
        uses: docker/build-push-action@v6
        id: push-snowflake-standalone
        with:
          context: tor/snowflake-standalone/
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/snowflake-standalone:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest-snowflake-standalone
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/snowflake-standalone
          subject-digest: ${{ steps.push-snowflake-standalone.outputs.digest }}
          push-to-registry: true